name: teller_trust
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+7

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_url_launcher: ^0.0.7
  shared_preferences: ^2.2.0
  flutter_carousel_slider: ^1.1.0
  animated_snack_bar: ^0.3.1
  cross_connectivity: any # specify a version if known
  equatable: any # specify a version if known
  otp_text_field: ^1.1.3
  flutter_bloc: any # specify a version if known
  google_fonts: any # specify a version if known
  lottie: any # specify a version if known
  flutter_typeahead: any # specify a version if known
  http: any # specify a version if known
  tuple: ^2.0.2
  #webview_flutter: ^4.10.0
  modal_bottom_sheet: ^3.0.0-pre
  pin_plus_keyboard: ^2.0.6
  persistent_bottom_nav_bar: ^4.0.2
  device_info_plus: any # specify a version if known
  local_auth: ^2.1.8
  custom_pin_screen: ^0.3.0
  dio: any # specify a version if known
  flutter_pw_validator: ^1.5.0
  rflutter_alert: ^2.0.6
  #flutter_vibrate: ^1.3.0
  loading_animation_widget: ^1.2.0+2
  shimmer_animation: any # specify a version if known
  dotted_border: ^2.1.0
  provider: ^6.0.2
  adaptive_theme: ^3.0.0
  idle_detector_wrapper: ^1.0.0
  #disk_space_update: ^0.0.2
  syncfusion_flutter_pdf: ^25.2.4
  permission_handler: ^11.3.1
  screenshot: ^3.0.0
  share_plus: ^10.0.2
  image_picker: ^1.1.1
  either_dart: ^1.0.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  infinite_scroll_pagination:
  encrypt: ^5.0.0
  #flutter_native_contact_picker: ^0.0.7
  async:
  firebase_core: ^2.24.2
  firebase_messaging:
  flutter_local_notifications:
  mime:
  http_parser: ^4.0.0
  flutter_image_compress: ^2.3.0
  image_cropper:
  pdf: ^3.11.1
  printing: ^5.13.2
  android_intent_plus:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.3.0

dependency_overrides:
  meta: 1.12.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/icons/networkCenter/
    - assets/icons/sendBeneficiary/
